function createfigure(xdata1, ydata1, zdata1)
%CREATEFIGURE(xdata1, ydata1, zdata1)
%  XDATA1:  contour x
%  YDATA1:  contour y
%  ZDATA1:  contour z

%  Auto-generated by MATLAB on 29-Mar-2025 23:15:37

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create contour
[c1,h1] = contour(xdata1,ydata1,zdata1,'LevelList',[0 1 2]);

% The following line demonstrates an alternative way to create a data tip.
% datatip(h1,-92,64);
% Create datatip
datatip(h1,'DataIndex',1773);

% Create ylabel
ylabel('w2');

% Create xlabel
xlabel('w1');

% Create title
title('2-Dominance Regions (1 = 2-dominant, 0 = not 2-dominant)');

box(axes1,'on');
axis(axes1,'tight');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'BoxStyle','full','Layer','top');
% Create colorbar
colorbar(axes1);

